apiVersion: v1
kind: Service
metadata:
  name: quota-operator-metrics
  namespace: default
  labels:
    app: quota-operator
spec:
  selector:
    app: quota-operator
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quota-operator
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: quota-operator
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics