apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-controller-manager
  labels:
    app: quota-operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: quota-operator
  template:
    metadata:
      labels:
        app: quota-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10